In [2]:
import pandas as pd
import numpy as np

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [4]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [5]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [7]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [8]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [9]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [10]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [11]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [12]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [13]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
   ....:                      [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [16]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [18]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [19]:
data[4] = np.nan

In [20]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [21]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [23]:
df.iloc[:4, 1] = np.nan

In [24]:
df.iloc[:2, 2] = np.nan

In [25]:
df

0         1         2
0  0.366998       NaN       NaN
1 -0.655606       NaN       NaN
2 -1.930378       NaN  0.403085
3 -0.645513       NaN  0.370810
4  1.293933  0.163346 -0.447223
5 -0.403255  0.723643  0.816024
6 -0.053245  1.069179 -0.131843

In [26]:
df.dropna()

0         1         2
4  1.293933  0.163346 -0.447223
5 -0.403255  0.723643  0.816024
6 -0.053245  1.069179 -0.131843

In [27]:
df.dropna(thresh=2)

0         1         2
2 -1.930378       NaN  0.403085
3 -0.645513       NaN  0.370810
4  1.293933  0.163346 -0.447223
5 -0.403255  0.723643  0.816024
6 -0.053245  1.069179 -0.131843

In [28]:
df.fillna(0)

0         1         2
0  0.366998  0.000000  0.000000
1 -0.655606  0.000000  0.000000
2 -1.930378  0.000000  0.403085
3 -0.645513  0.000000  0.370810
4  1.293933  0.163346 -0.447223
5 -0.403255  0.723643  0.816024
6 -0.053245  1.069179 -0.131843

In [29]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.366998  0.500000  0.000000
1 -0.655606  0.500000  0.000000
2 -1.930378  0.500000  0.403085
3 -0.645513  0.500000  0.370810
4  1.293933  0.163346 -0.447223
5 -0.403255  0.723643  0.816024
6 -0.053245  1.069179 -0.131843

In [30]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [31]:
df.iloc[2:, 1] = np.nan

In [32]:
df.iloc[2:, 1] = np.nan

In [33]:
df

0         1         2
0  1.476396 -0.170829 -0.283763
1  0.557417 -1.593274 -0.304194
2 -0.134891       NaN  0.330503
3  0.124144       NaN -2.676174
4 -1.348109       NaN -1.842365
5  0.049046       NaN  0.138965

In [34]:
df.fillna(method="ffill")

0         1         2
0  1.476396 -0.170829 -0.283763
1  0.557417 -1.593274 -0.304194
2 -0.134891 -1.593274  0.330503
3  0.124144 -1.593274 -2.676174
4 -1.348109 -1.593274 -1.842365
5  0.049046 -1.593274  0.138965

In [35]:
df.fillna(method="ffill", limit=2)

0         1         2
0  1.476396 -0.170829 -0.283763
1  0.557417 -1.593274 -0.304194
2 -0.134891 -1.593274  0.330503
3  0.124144 -1.593274 -2.676174
4 -1.348109       NaN -1.842365
5  0.049046       NaN  0.138965

In [36]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [37]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [38]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
   ....:                      "k2": [1, 1, 2, 3, 3, 4, 4]})

In [39]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [40]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [41]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [42]:
data["v1"] = range(7)

In [43]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [44]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [45]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [46]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
   ....:                               "pastrami", "corned beef", "bacon",
   ....:                               "pastrami", "honey ham", "nova lox"],
   ....:                      "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [47]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [48]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [49]:
data["animal"] = data["food"].map(meat_to_animal)

In [50]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [51]:
def get_animal(x):
   ....:     return meat_to_animal[x]

In [52]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [53]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [54]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [55]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [56]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [57]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [58]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
   ....:                     index=["Ohio", "Colorado", "New York"],
   ....:                     columns=["one", "two", "three", "four"])

In [59]:
def transform(x):
   ....:     return x[:4].upper()

In [60]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [61]:
data.index = data.index.map(transform)

In [62]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [63]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [64]:
data.rename(index={"OHIO": "INDIANA"},
   ....:             columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [65]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [66]:
bins = [18, 25, 35, 60, 100]


In [67]:
age_categories = pd.cut(ages, bins)

In [68]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [69]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [70]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [71]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [72]:
pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [73]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [74]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [75]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [76]:
data = np.random.uniform(size=20)

In [77]:
pd.cut(data, 4, precision=2)

[(0.52, 0.72], (0.11, 0.31], (0.72, 0.92], (0.11, 0.31], (0.11, 0.31], ..., (0.72, 0.92], (0.11, 0.31], (0.11, 0.31], (0.52, 0.72], (0.31, 0.52]]
Length: 20
Categories (4, interval[float64, right]): [(0.11, 0.31] < (0.31, 0.52] < (0.52, 0.72] < (0.72, 0.92]]

In [78]:
data = np.random.standard_normal(1000)

In [79]:
quartiles = pd.qcut(data, 4, precision=2)

In [80]:
quartiles

[(0.67, 2.78], (-2.75, -0.73], (-0.73, -0.05], (-2.75, -0.73], (0.67, 2.78], ..., (-0.05, 0.67], (-0.05, 0.67], (0.67, 2.78], (0.67, 2.78], (-0.05, 0.67]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.75, -0.73] < (-0.73, -0.05] < (-0.05, 0.67] < (0.67, 2.78]]

In [81]:
pd.value_counts(quartiles)

(-2.75, -0.73]    250
(-0.73, -0.05]    250
(-0.05, 0.67]     250
(0.67, 2.78]      250
dtype: int64

In [82]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.739, -1.335]     100
(-1.335, -0.0503]    400
(-0.0503, 1.309]     400
(1.309, 2.783]       100
dtype: int64

In [83]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [84]:
 data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.005261     0.003020     0.038375    -0.020922
std       1.016340     0.990009     1.019357     0.967631
min      -3.215844    -3.099756    -3.468315    -3.028719
25%      -0.719938    -0.662220    -0.659418    -0.660797
50%      -0.027617    -0.006830     0.000441    -0.048184
75%       0.666632     0.669936     0.684571     0.627253
max       3.116423     3.751739     3.525159     3.001401

In [85]:
col = data[2]

In [86]:
col[col.abs() > 3]

66     3.454611
83     3.035269
345    3.195034
544   -3.468315
575   -3.116284
593    3.525159
807    3.152034
Name: 2, dtype: float64

In [87]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
22  -1.111946  3.349823  0.180470 -0.681175
66   0.653768 -1.121407  3.454611  1.517178
83  -0.013309 -0.610743  3.035269  2.130787
137 -0.239636 -1.358498 -0.080857 -3.028719
316 -3.013382  1.126158  0.801955 -1.149637
327  0.151779 -1.179812  0.682756  3.001401
345  1.629967  1.256645  3.195034 -1.162639
438 -0.846909 -3.099756 -0.300814 -0.263674
476 -0.588076  3.015797 -0.586798 -0.082356
544 -0.852892  1.028650 -3.468315 -0.330627
575  1.850699 -0.237028 -3.116284 -1.063566
593 -0.696087 -0.492969  3.525159 -0.698677
678 -0.414451 -3.023987  0.063120 -1.087698
726 -1.230657  3.751739 -0.962600  1.978070
807  0.702411 -0.368760  3.152034  0.977032
838 -3.215844  0.438848  0.663664  0.399352
863  3.116423  1.385451  0.893167 -1.052316

In [88]:
data[data.abs() > 3] = np.sign(data) * 3

In [89]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.005148     0.002026     0.037598    -0.020895
std       1.015289     0.985885     1.013251     0.967538
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.719938    -0.662220    -0.659418    -0.660797
50%      -0.027617    -0.006830     0.000441    -0.048184
75%       0.666632     0.669936     0.684571     0.627253
max       3.000000     3.000000     3.000000     3.000000

In [90]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0  1.0  1.0
1  1.0  1.0  1.0 -1.0
2 -1.0 -1.0  1.0 -1.0
3 -1.0  1.0  1.0 -1.0
4  1.0 -1.0 -1.0 -1.0

In [91]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [92]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [93]:
sampler = np.random.permutation(5)

In [94]:
sampler

array([1, 0, 4, 3, 2])

In [95]:
df.take(sampler)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [96]:
df.iloc[sampler]

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [97]:
column_sampler = np.random.permutation(7)

In [98]:
column_sampler

array([0, 3, 5, 1, 6, 4, 2])

In [99]:
df.take(column_sampler, axis="columns")

0   3   5   1   6   4   2
0   0   3   5   1   6   4   2
1   7  10  12   8  13  11   9
2  14  17  19  15  20  18  16
3  21  24  26  22  27  25  23
4  28  31  33  29  34  32  30

In [100]:
df.sample(n=3)

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6

In [101]:
choices = pd.Series([5, 7, -1, 6, 4])

In [102]:
choices.sample(n=10, replace=True)

4    4
0    5
1    7
4    4
2   -1
3    6
2   -1
2   -1
2   -1
4    4
dtype: int64

In [103]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
   .....:                    "data1": range(6)})

In [104]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [105]:
pd.get_dummies(df["key"])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [106]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [107]:
df_with_dummy = df[["data1"]].join(dummies)

In [108]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [109]:
mnames = ["movie_id", "title", "genres"]

In [110]:
movies = pd.read_table("datasets/movielens/movies.dat", sep="::",
   .....:                        header=None, names=mnames, engine="python")

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/movielens/movies.dat'

In [111]:
movies[:10]

NameError: name 'movies' is not defined

In [112]:
np.random.seed(12345)

In [113]:
values = np.random.uniform(size=10)

In [114]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [115]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [116]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [117]:
s = pd.Series([1, 2, 3, None])

In [118]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [119]:
s.dtype

dtype('float64')

In [120]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [121]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [122]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [123]:
s.dtype

Int64Dtype()

In [124]:
s[3]

<NA>

In [125]:
s[3] is pd.NA

True

In [126]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [127]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [128]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [129]:
df = pd.DataFrame({"A": [1, 2, None, 4],
   .....:                    "B": ["one", "two", "three", None],
   .....:                    "C": [False, None, False, True]})

In [130]:
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [131]:
df["A"] = df["A"].astype("Int64")

In [132]:
df["B"] = df["B"].astype("string")

In [133]:
df["C"] = df["C"].astype("boolean")

In [134]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

In [135]:
val = "a,b,  guido"

In [136]:
val.split(",")

['a', 'b', '  guido']

In [137]:
pieces = [x.strip() for x in val.split(",")]

In [138]:
pieces

['a', 'b', 'guido']

In [139]:
first, second, third = pieces

In [140]:
first + "::" + second + "::" + third

'a::b::guido'

In [141]:
"::".join(pieces)

'a::b::guido'

In [142]:
"guido" in val

True

In [143]:
val.index(",")

1

In [144]:
val.find(":")

-1

In [145]:
val.index(":")

ValueError: substring not found

In [146]:
val.count(",")

2

In [147]:
val.replace(",", "::")

'a::b::  guido'

In [148]:
val.replace(",", "")

'ab  guido'

In [149]:
import re

In [150]:
text = "foo    bar\t baz  \tqux"

In [152]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [153]:
regex = re.compile(r"\s+")

In [154]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [155]:
regex.findall(text)

['    ', '\t ', '  \t']

In [156]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes the regex case insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

In [157]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [158]:
m = regex.search(text)

In [160]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [161]:
text[m.start():m.end()]

'dave@google.com'

In [162]:
print(regex.match(text))

None


In [163]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [164]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [165]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [166]:
m = regex.match("wesm@bright.net")

In [167]:
m.groups()

('wesm', 'bright', 'net')

In [168]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [169]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [170]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
   .....:         "Rob": "rob@gmail.com", "Wes": np.nan}

In [171]:
data = pd.Series(data)

In [172]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [173]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [174]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [175]:
data_as_string_ext = data.astype('string')

In [176]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [177]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [178]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [179]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [180]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]


In [181]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [182]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [183]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [184]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [185]:
values = pd.Series(['apple', 'orange', 'apple',
   .....:                     'apple'] * 2)

In [186]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [187]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [188]:
values = pd.Series([0, 1, 0, 0] * 2)

In [189]:
dim = pd.Series(['apple', 'orange'])

In [190]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [191]:
dim

0     apple
1    orange
dtype: object

In [192]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [195]:
fruit_cat = df['fruit'].astype('category')

KeyError: 'fruit'

In [194]:
fruit_cat

NameError: name 'fruit_cat' is not defined

In [196]:
 my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [197]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [198]:
categories = ['foo', 'bar', 'baz']

In [199]:
codes = [0, 1, 2, 0, 0, 1]

In [200]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [201]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [202]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [203]:
rng = np.random.default_rng(seed=12345)

In [204]:
draws = rng.standard_normal(1000)

In [205]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [206]:
bins = pd.qcut(draws, 4)

In [207]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [208]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [209]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [210]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [211]:
bins = pd.Series(bins, name='quartile')

In [212]:
results = (pd.Series(draws)
   .....:            .groupby(bins)
   .....:            .agg(['count', 'min', 'max'])
   .....:            .reset_index())


In [213]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [214]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [215]:
N = 10_000_000


In [216]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [217]:
categories = labels.astype('category')

In [218]:
labels.memory_usage(deep=True)

600000128

In [219]:
categories.memory_usage(deep=True)

10000540

In [220]:
%time _ = labels.astype('category')

CPU times: user 334 ms, sys: 7.4 ms, total: 341 ms
Wall time: 339 ms


In [221]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [222]:
cat_s = s.astype('category')

In [223]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [224]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [225]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [226]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [227]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [228]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
dtype: int64

In [229]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
dtype: int64

In [230]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [231]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [232]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [233]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [234]:
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1